// <auto-generated />
using System;
using ArcaneVault.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcaneVault.API.Migrations
{
    [DbContext(typeof(ArcaneVaultDbContext))]
    partial class ArcaneVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCategories", b =>
                {
                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryCode");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCollectionItemCategories", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "CategoryCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCollectionItems", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("UserName");

                    b.ToTable("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultUsers", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "admin",
                            Email = "admin@arcanevault.com",
                            IsDeleted = false,
                            PasswordHash = "$2a$12$R9h/cIPz0gi.URNNV3kh2OPST9/PgBkqquzi.Ee4kGXpVuLxNs.lq",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("ArcaneVault.API.Data.FixedDepositAccounts", b =>
                {
                    b.Property<int>("FDAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccruedInterest")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("AmountReceived")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQuarterlyCompounding")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenureMonths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WithdrawalDate")
                        .HasColumnType("TEXT");

                    b.HasKey("FDAccountId");

                    b.HasIndex("UserName");

                    b.ToTable("FixedDepositAccounts");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.FixedDepositTransactions", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccrualPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FDAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("FDAccountId");

                    b.ToTable("FixedDepositTransactions");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.MarketplaceListing", b =>
                {
                    b.Property<int>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AskingPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ListedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellerUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradePreferences")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListingId");

                    b.HasIndex("ItemId");

                    b.ToTable("MarketplaceListings");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuyerUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OfferedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OfferedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("ParentOfferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerResponse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TradeItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OfferId");

                    b.HasIndex("ListingId");

                    b.HasIndex("ParentOfferId");

                    b.HasIndex("TradeItemId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("WishlistId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserName");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCollectionItemCategories", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultCategories", "Category")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("CategoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultCollectionItems", "CollectionItem")
                        .WithMany("CollectionItemCategories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCollectionItems", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultUsers", "User")
                        .WithMany("CollectionItems")
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultUsers", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultRoles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.FixedDepositAccounts", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.FixedDepositTransactions", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.FixedDepositAccounts", "FDAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("FDAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FDAccount");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.MarketplaceListing", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultCollectionItems", "CollectionItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.Offer", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.MarketplaceListing", "Listing")
                        .WithMany("Offers")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcaneVault.API.Data.Offer", "OriginalOffer")
                        .WithMany("CounterOffers")
                        .HasForeignKey("ParentOfferId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultCollectionItems", "TradeItem")
                        .WithMany()
                        .HasForeignKey("TradeItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Listing");

                    b.Navigation("OriginalOffer");

                    b.Navigation("TradeItem");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.Wishlist", b =>
                {
                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultCollectionItems", "CollectionItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcaneVault.API.Data.ArcaneVaultUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCategories", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultCollectionItems", b =>
                {
                    b.Navigation("CollectionItemCategories");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultRoles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.ArcaneVaultUsers", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.FixedDepositAccounts", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.MarketplaceListing", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("ArcaneVault.API.Data.Offer", b =>
                {
                    b.Navigation("CounterOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
